### ISSUE TITLE
IE9: 'Uint8Array' is undefined

### ISSUE THREAD

**Issue by dgsunesen** [taunus/taunus#11]
When starting taunus in IE9, I get this error in urlparser.js

line 952:
```var ret = new Uint8Array(128);```

**Comment by dgsunesen** [comment]
I see this is not supported in IE9 - is there a way to work around this in taunus?

**Comment by bevacqua** [comment]
The issue in this case is that we're using `fast-url-parser`, we should look for ways to get rid of this dependency as it's quite sizable

**Comment by bevacqua** [comment]
It makes up for almost 1/3 of the client-side footprint, too

![image](https://cloud.githubusercontent.com/assets/934293/8083968/9b1fc774-0f5e-11e5-8233-509217d1c957.png)

**Comment by bevacqua** [comment]
[omnibox](https://github.com/bevacqua/omnibox) should resolve both issues

**Comment by bevacqua** [comment]
Fixed in `6.1.5`. Let me know if there are any outstanding issues in IE9/10.
