### ISSUE TITLE
Why are there exact dependencies' versions specified?

### ISSUE THREAD

**Issue by zardak** [taunus/taunus#13]
Why not rely on semver?
That said, your CI build is failing atm due to this problem.

**Comment by bevacqua** [comment]
Because immutability

**Comment by zenflow** [comment]
Could you explain? I know the meaning of the word "immutability" (fixed or unchanging) but I don't see how it explains why this package has pinned dependency versions. 
Couldn't [caret ranges](https://github.com/npm/node-semver#caret-ranges-123-025-004) be used to guarantee that the latest patch version is used? As long as these dependencies' maintainers are following semver, there is no chance that it will break Taunus, and it may resolve edge-case issues before we even know about them!
