### ISSUE TITLE
something missing in the getting started guide

### ISSUE THREAD

**Issue by boynet** [taunus/taunus#14]
search for "rm layout.js"
after removing the file and creating the new layout.jade it dosent say what to put in layout.jade.. ofcourse from this point the whole guide not working.

**Comment by boynet** [comment]
find out it should be:
````
title=model.title
main!=partial
script(src='/js/all.js')
````

anyway finished the guide and I still very confused..
I think there should be more step that create a new view and make a link to it to show server rendering vs client rendering..
right now it looks to me like you anyway need to write the code twice in server and in client so I cant understand where the Isomorphic part excepet from the router

**Comment by bevacqua** [comment]
+@ivancevich

**Comment by ivancevich** [comment]
Hey @boynet we'll be working on improving the getting started guide as well as the documentation for Taunus during the next week. Also, I recommend you to check https://github.com/taunus/taunus-todomvc to have a deeper idea of what you can do with Taunus :)

**Comment by bevacqua** [comment]
Documentation site is no longer maintained
