### ISSUE TITLE
Working with data returned from an xhr request

### ISSUE THREAD

**Issue by neurotech** [taunus/taunus#15]
I've worked my way through the Getting Started page and am having some trouble wrapping my head around some things.

How do I write a controller that:

 1. Makes a **GET** request to `exampleurl/api/status`
 2. Passes the response (in the form of an array of objects) as the `model` to a view, in this case `views/home/index.jade`

*Then,* how do I work with the model in `views/home/index.jade`? i.e. iterate over the array and render values from the contained objects in my view, etc.

P.S. I'm using `hapi`, `taunus-hapi`, and `hapiify`.

**Comment by dgsunesen** [comment]
Giving you have a model in your controller (controllers/home/index.js), that looks like this.

```
module.exports = function(req, res, next) {
  res.viewModel = {
    model: {
      title: 'Home',
      posts: {},
      path: req.path,
    }
  };

  populate();

  function populate() {
    // Make your GET request here, e.g. through somekind of promise
    // Example code.
    Feed.getData().then(function(data) {
      res.viewModel.model.posts = data;

      next();
    });
  }
};
```

Then within your view (view/home/index.jade), you should be able to do:

```
each post in posts
   // your post HTML here.
```

**Comment by neurotech** [comment]
Thanks @dgsunesen. I couldn't sleep and ended up coming back to this and solving it.

I had mistakenly written my jade as:

```jade
each item in model.status
```

Rather than:

```jade
each item in status
```

A definite head-slapping moment.

**Comment by neurotech** [comment]
Reopening to ask this.

How do I use `taunus.xhr` in a controller properly?

This code does not work:

```javascript
// /controllers/home/index.js
var uri = '/example/status';

module.exports = function (request, reply) {
  taunus.xhr(uri, function (err, body) {
    reply({
      model: {
        status: body
      }
    });
  });
};
```

When I load my home/index view in a browser, I get this error in my application:

```
Debug: internal, implementation, error
    TypeError: Uncaught error: undefined is not a function
    at Object.module.exports [as actionFn] (/Users/timdouglas/tmp/taunus/controllers/home/index.js:7:10)
    at handler (/Users/timdouglas/tmp/taunus/node_modules/taunus-hapi/taunus-hapi.js:29:13)
    at Object.internals.handler (/Users/timdouglas/tmp/taunus/node_modules/hapi/lib/handler.js:93:36)
    at /Users/timdouglas/tmp/taunus/node_modules/hapi/lib/handler.js:28:23
    at internals.Protect.run (/Users/timdouglas/tmp/taunus/node_modules/hapi/lib/protect.js:56:5)
    at exports.execute (/Users/timdouglas/tmp/taunus/node_modules/hapi/lib/handler.js:22:22)
    at /Users/timdouglas/tmp/taunus/node_modules/hapi/lib/request.js:370:13
    at iterate (/Users/timdouglas/tmp/taunus/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/Users/timdouglas/tmp/taunus/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /Users/timdouglas/tmp/taunus/node_modules/hapi/node_modules/hoek/lib/index.js:841:22
```

**Comment by dgsunesen** [comment]
You cannot since it's a client-side method.

Have a look at this package: https://www.npmjs.com/package/request

**Comment by neurotech** [comment]
Ah yes, of course. Thank you.

I ended up going with `got` https://github.com/sindresorhus/got
