### ISSUE TITLE
Taunusrc path resolve

### ISSUE THREAD

**Issue by radum** [taunus/taunus#16]
I have a taunusrc file like this:

```js
{
	"views": ".bin/views",
	"client_wiring": ".bin/wiring.js"
}
```

Running my app locally works ok, but running on a Ubuntu 16 server fails with the error:

`Missing server-side controller for "home/index" action. Searched location: "/controllers/home/index"`

Looking how the file is read I saw you are using path.resolve.

```js
var pkg = path.resolve('./package.json');
var rc = path.resolve('.taunusrc');
```

Now if my node app on the server runs under a user that has the home path set to the root folder where the main app is, then path.resolve will resolve to `/.taunusrc` and to `/package.json` and it will fail to read these 2 files because they are not in the root folder of the server. And node is not resolving them from the root path of the app from where the user is running it.

Now I'm not sure how to fix this, because I wouldn't change my server setup for security reasons. I think it will be great if we can send these options via the app itself and not from external files.

Am I missing anything?

**Comment by bevacqua** [comment]
Why would you set `HOME` to `/`? I never heard of such thing

**Comment by radum** [comment]
@bevacqua You misunderstood me, the HOME is where the app folder is, it is *not* under `/`

The problem is that path.resolve - resolves the file as `/.taunusrc` and not in the app folder.

**Comment by bevacqua** [comment]
Right, `path.resolve` uses the current working directory. Run the app from the app directory and you'll be okay.

**Comment by radum** [comment]
Thanks @bevacqua :) I was running a service to start / restart my app, and I just realized I could configure my service to run from the app dir using `WorkingDirectory=/app_path`.

This will tell the service to run the `ExecStart` from that location, and this fixes my issue without having to run the app from that folder manually.
