### ISSUE TITLE
Safari only error..: TypeError: undefined is not a function (evaluating 'done(null)')

### ISSUE THREAD

**Issue by dgsunesen** [taunus/taunus#3]
Every time I start up my taunus application I get this error in Safari, preventing it from working.

The done-method is located here:

'node_modules/taunus/browser/stores/idb.js'

What could cause this problem, and does anyone have any idea on how to fix it?

Edit: here is a screenshot of the error

![screen shot 2015-02-05 at 13 17 07](https://cloud.githubusercontent.com/assets/1023815/6060107/f299c6d0-ad39-11e4-9ab0-8eb2749509f3.png)

**Comment by bevacqua** [comment]
This is an IndexedDB cross-browser error in our end. I'll look into it.

**Comment by dgsunesen** [comment]
Thanks a lot..! It seems to be a problem on iOS Chrome and iOS Safari as well.

**Comment by bevacqua** [comment]
This was a big issue, and it's resolved in `4.1.7`. Thank you for reporting it!

**Comment by dgsunesen** [comment]
Awesome job! Thanks!

**Comment by bevacqua** [comment]
Let me know if it's not working as expected.



github <https://github.com/bevacqua> · blog <http://blog.ponyfoo.com/> ·
twitter <https://twitter.com/nzgb> · book <http://bevacqua.io/buildfirst> ·
career <http://careers.stackoverflow.com/bevacqua> ·about
<http://bevacqua.io/>

**Comment by dgsunesen** [comment]
Works like a charm!
