### ISSUE TITLE
Uncaught Error: Fetching JSON data model failed at mountpoint.

### ISSUE THREAD

**Issue by dgsunesen** [taunus/taunus#5]
Hi,

This error seems to occur a bit randomly. 

In my server-side controllers, I fetch data using AJAX, and one of my server-side controllers look like this:

```javascript
'use strict';

var XHR = require('../../utilities/xhr');
var Utils = require('../../utilities/utils');

module.exports = function(req, res, next) {
  res.viewModel = {
    model: {
      title: 'Your feed',
      posts: {},
      prefetched: {},
      path: req.path,
      meta: {
        description: 'This is a description'
      }
    }
  };

  populate();

  function populate() {
    XHR.getData('Feed', '10', '0', 'feed').then(function(data) {
      res.viewModel.model.posts = Utils.hydrateData(data);
      populatePrefetch();
    });
  }

  function populatePrefetch() {
    XHR.getData('Feed', '10', '10', 'feed').then(function(data) {
      res.viewModel.model.prefetched = Utils.hydrateData(data);
      next();
    });
  }
};
```

The XHR.getData() method (where I utilize https://github.com/request/request)

```javascript
getData: function(env, limit, skip, access) {
    var response = request({
      url: 'http://api/url/here' + env + '?limit=' + limit + '&skip=' + skip + '&access=' + access,
      method: 'POST',
      headers: {
        'Authorization': 'Basic blasdfasdfasdf'
      }
    });

    return response.then(function(res) {
      if (res[0].statusCode !== 200) {
        console.log('getData', res);
        throw new Error('Server responded with status code ' + res[0].statusCode)
      } else {
        return JSON.parse(res[0].body)
      }
    }).fail(function (error) {
      console.log(error);
    });
  }
```

The Utils.hydrateData() just adds a little something extra to my JSON, nothing special there.

The stack trace of the error is as follows:
![screen shot 2015-03-03 at 15 36 11](https://cloud.githubusercontent.com/assets/1023815/6464525/193d5d98-c1bb-11e4-88b7-b586bc8fdd55.png)

And when it's successful, it looks like this:
![screen shot 2015-03-03 at 15 37 19](https://cloud.githubusercontent.com/assets/1023815/6464553/48aaf5fe-c1bb-11e4-8e3c-d62f1f6f56c6.png)

On the client-side, I use the same XHR.getData() method to retrieve data (within an infinite scroll module) and I get no errors there.

**Comment by bevacqua** [comment]
What does the request to `/feed?json` yield, in the Network tab?

**Comment by dgsunesen** [comment]
![screen shot 2015-03-03 at 15 54 19](https://cloud.githubusercontent.com/assets/1023815/6464881/9a8580a4-c1bd-11e4-9a82-d851a508e115.png)

**Comment by bevacqua** [comment]
So you never actually got a response, what if the server-side controller looks like this?

```js
function (req, res, next) {

  res.viewModel = {
    model: {
      title: 'Your feed',
      posts: {},
      prefetched: {},
      path: req.path,
      meta: {
        description: 'This is a description'
      }
    }
  };
  next();
}
```

Does it ever fail in this case?

**Comment by dgsunesen** [comment]
Nope, I doesn't fail then. However, I don't have any data to display then.

**Comment by bevacqua** [comment]
Right. I would review the async logic for fetching data with the "XHR" thing

**Comment by dgsunesen** [comment]
Could really slow repsonse times be the cause?.. The API i'm using atm has quite a high latency

**Comment by bevacqua** [comment]
Well if the issue is intermittent that might mean the API sometimes fails due to high latency, but Taunus doesn't impose any timeouts on ajax.
