### ISSUE TITLE
taunus.render does not update DOM

### ISSUE THREAD

**Issue by dgsunesen** [taunus/taunus#6]
Hi,

I'm experiencing problems with taunus.render not rendering and updating my DOM element. I'm using the debugger, and it says "[view] rendering partials/likes-counter with model" and the correct model is passed.

```
var model = {
          post: {
            media: {
              expanded_likes: [
                {
                  username: 'something'
                },
                {
                  username: 'blablabla'
                }
              ]
            }
          }
        };



        taunus.partial(recentLikes, 'partials/likes-counter', model);
```

This is how my code looks like.

**Comment by bevacqua** [comment]
How does `taunus.state.templates['partials/likes-counter']` look like?

**Comment by dgsunesen** [comment]
Hm.. It gives me ```undefined```

**Comment by bevacqua** [comment]
It should be a function. How are you importing your views?

**Comment by dgsunesen** [comment]
What should be a function? Just so that I understand :)

**Comment by bevacqua** [comment]
`taunus.state.templates['partials/likes-counter']`

**Comment by dgsunesen** [comment]
All right. Well, I've looked through your pony foo examples code and done the same as you do in compose.js on line 129

**Comment by bevacqua** [comment]
Like I said, you are not including the `likes-counter` view, has nothing to do with how you plan on using it.
