### ISSUE TITLE
Riotjs as a view engine?

### ISSUE THREAD

**Issue by zelid** [taunus/taunus#8]
Is it possible somehow integrate https://github.com/muut/riotjs as a view engine to Taunus?

Riotjs is a mciro-view engine that takes one-way data flow paradigm of React and is x20 times smaller than React. The only thing it misses is a good routing that work on both client and server (it has only hashbang client-side routing bundled) and example how to use it right with isomorphic environment.

Taunus solves the issue with routing and isomorphic environment and it would be great to combine both together. 

What do you think about adding a Riotjs view engine to Taunus?

**Comment by bevacqua** [comment]
As long as it can produce methods that take a model and return an HTML string, you could use RiotJS with Taunus

**Comment by zelid** [comment]
It can get model and return an HTML string.

I'm trying to make something.

This issue with those React-kind of view engines have no parent layout inheritance that we used to have in MVC template engines.

You have a parent component mounted somewhere on HTML page and it can include other components inside.

Right now I do something very basic with 3 components:
app
product-list
product-details

On the root '/' route I can easily render app components with product list inside, but when the route '/product-details' is called I can't just render 'product-details' view that will take it's parent layout, I need to render 'app' and make sure that it will include 'product-details' component inside it instead of 'product-list' component as it was with '/' route.

The obvious solution is to use large switch-case of components to show based on the current route or some model property inside of 'app' component. It doesn't look elegant, but I have no other ideas as for now.

**Comment by bevacqua** [comment]
That sounds like a decent convention
