### ISSUE TITLE
Question: since we bring our own view engine...

### ISSUE THREAD

**Issue by bitinn** [taunus/taunus#9]
We probably need to deal with the more difficult problem of correctly binding client-side virtual dom to server-regenerated real dom on first-page, right?

`React` appear to be the only library that attempts to do it, `virtual-dom` [and others](http://vdom-benchmark.github.io/vdom-benchmark/) have avoided it, for rendering performance and ease of implementation I believe.

Others and I have asked about this topic before (see https://github.com/Matt-Esch/virtual-dom/issues/227), IMHO, the simplest approach is to re-render those dom when client-side js/data has been loaded.

What's your opinion on this aspect?

**Comment by bevacqua** [comment]
Views can be any function that takes in a `model` and yields some HTML. That's the abstraction I mean by "bring your own view engine". On the server-side, that function gets called for both the view and the layout, and the resulting HTML is sent to the client.

On the client-side, `taunus` currently assigns the result of rendering the view to the `innerHTML` property on the container. I would love to do research and pour time into considering [diferente](https://github.com/bevacqua/diferente) for that _(which is actually quite small, 6.48kb min/gzip)_.

**Comment by bitinn** [comment]
Thx, I need to look more into it, on first sight it looks like you still need to replace/wipe existing server-rendered dom then attach whatever events you need? I am not sure how React does it, but it appears can see real dom is same as virtual dom, and only attach event without destroying existing dom.

**Comment by bevacqua** [comment]
When it comes to binding events and whatnot the controllers are in charge of that. Server-side renders HTML and then client-side controller kicks in. If the client-side renders the HTML the client-side controller still kicks in, so it's not really related. I think the only kind of bug that could come up from that is if the user navigates to the same view and we attempt to re-render it, but we don't really touch the DOM because the HTML is identical. In that case the controller would probably re-bind events that are already bound.

**Comment by bitinn** [comment]
Thing is, if you use virtual-dom like approach, aren't events declared in your render function?

So there isn't a controller to bind events explicitly, all you would do is to run render function on client-side and replace existing real dom. Your generated real dom will have events.

To replace dom, you are suggesting we use a html parser (`htmlparser2`) or use innerHTML (`diferente` or `diffhtml`) to convert real dom into virtual dom, then diff and patch them with your generated dom, right?

**Comment by bevacqua** [comment]
You'd take an HTML string into `diffhtml` which creates the vdom tree, diffs and patches on `el`, yes. About event binding I guess you're right, I don't have a lot of exp. using vdom, but there's still events bound by libraries and whatnot to be considered

**Comment by bitinn** [comment]
Cheers. I think I have some idea to go on now.
